### ISSUE TITLE
Текстуры

### ISSUE THREAD

**Issue by Kor-Angar** [dosinabox/g1_steam_fix#2]
а скинь плиз архив из текстурами. я читал что у тебя что то исправленное было в них.

**Comment by dosinabox** [comment]
Под рукой нет. Возьми snowball_main.vdf / russobit_main.vdf из Data. Не помню что там помимо русских загрузочных экранов, фонов и картинок сохранений.

**Comment by Kor-Angar** [comment]
я уже нашёл. не мог просто распаковать инсталлер :-) 

на форуме было написано что тектсуры доспехов правились

**Comment by dosinabox** [comment]
ты про стим-фикс Г1 или мод-фикс для Руссобита?

**Comment by Kor-Angar** [comment]
видимо я их перепутал :-)
