### ISSUE TITLE
Лишние навыки в окне персонажа в мод-фиксе Snowball

### ISSUE THREAD

**Issue by dosinabox** [dosinabox/g1_steam_fix#3]
![image](https://user-images.githubusercontent.com/39790055/155755457-d332b54c-b25e-4438-9c7e-64e37265c7cd.png)

**Comment by Kor-Angar** [comment]
это файл меню чей? :-)

**Comment by Kor-Angar** [comment]
твой датник? а где ты его взяла? или ты его сама писала? я брал шрифт из твоего архива  в воркшопе, но он у меня почему то другой

**Comment by Kor-Angar** [comment]
понятно

**Comment by dosinabox** [comment]
исправлено
