### ISSUE TITLE
Ошибка запуска под GPTK

### ISSUE THREAD

**Issue by LDS1** [dosinabox/g1_steam_fix#6]
Использую Apple Game Porting Tool Kit.

- ванильная стим готика запускается

- после установки стим фикса получаю ошибку:
<img width="162" alt="image" src="https://github.com/dosinabox/g1_steam_fix/assets/8604295/9e8c7c15-2c5f-44b2-bd91-afc7c36b7405">
Возможно, проблема в самом юнион

**Comment by dosinabox** [comment]
При установке была выбрана опция поддержки геймпада?

**Comment by LDS1** [comment]
> При установке была выбрана опция поддержки геймпада?

Нет, все чекбоксы пустые. Ставил на экспериментальную воркшоп бету

**Comment by dosinabox** [comment]
А для воркшоп беты лучше использовать подписки из самого воркшопа, не устанавливая стим фикс:
https://steamcommunity.com/sharedfiles/filedetails/?id=2787491081
https://steamcommunity.com/sharedfiles/filedetails/?id=2786604938

**Comment by LDS1** [comment]
Beta: none та же ситуация

**Comment by dosinabox** [comment]
Значит, дело в Юнионе и следует сообщить об этом Гратту.
